🔀 :: (#103) 활성화된 알림 카테고리 목록 api 변경
team-xquare/v1-service-notification pull request #224
Opened 2023-05-21 11:25 UTC by lyutvs

2023-05-21 12:05 UTC, jhhong0509 commented on notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
> +            }
`.find()` 말고 associate 함수로 Map 만들고 하면 더 나을듯

2023-05-21 12:05 UTC, jhhong0509 commented on notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
> +            }
그리고 카테고리별 알람 상태? 일 것 같은데, category를 기준으로 map 도는게 맞지 않나?

2023-05-22 02:29 UTC, leeseojune53 requested changes

2023-05-22 02:29 UTC, leeseojune53 commented on notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
> +        }
p3) 요쪽에 category의 topic을 substring하는건 category 도메인쪽에서 처리해주고, 사용하는 쪽에서는 it.shortTopic 같이 사용하는게 코드가 더 쉬울 것 같습니다

2023-05-22 02:29 UTC, leeseojune53 commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +            .where(categoryEntity.eq(settingEntity.settingId.categoryEntity))
p1) 여기는 다시 확인 부탁드립니다 :)
where문 안에서 settingEntity를 호출하는게 조금 이상하네요
+ 사용하지 않는 userId

2023-05-22 11:03 UTC, lyutvs commented on notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt
> +        }
달아주신 코멘트를 잘 이해한건지 모르겠어서 코드 리뷰 한번 더 부탁드립니다

2023-05-22 13:19 UTC, jungho1209 commented on notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt
> +        }
여기 throw 부분은 임시로 처리하신거 같은데 확인 부탁드립니다!

2023-05-23 14:22 UTC, leeseojune53 commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +                        it.topic.substringBefore("_"),
여기는 그냥 넘겨주지않고 왜 따로 처리하나요?

2023-05-23 14:22 UTC, leeseojune53 commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +                        it.topic.substringBefore("_"),
topic에 _ 처리하는 부분때문이라면 해당 부분은 그대로 넘겨주고, Domain쪽에서 따로 함수는 빼는게 좋을 것 같습니다
해당 코드를 보지 않으면 가져온 Entity가 _기준으로 왜 잘려있는지 모를 수 있으니까요 :)

2023-05-23 14:32 UTC, lyutvs commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +                        it.topic.substringBefore("_"),
Domain 쪽에서 따로 처리한다는 부분이 SettingApiImpl에서 topic _ 처리하는 private 메소드 같은걸 만들어서 처리 하라는 말씀이신가요??

2023-05-24 00:03 UTC, leeseojune53 commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +                        it.topic.substringBefore("_"),
private가 아니라 topic을 가져와서 사용할 때  setting.getTopicSubStringBy_ 이런걸로 서비스에서 호출해서 명시적으로 쓰자는거쥬
모델은 값 그대로 가지고있는게 좋다고 생각합니다
_로 substring하는 이유는 모르겠지만, 결국 DB상에는 전체가 저장되어있는거면 그걸 불러온 부분까지는 그대로 들고오는게 유지보수할 때 좋을 것 같아유

2023-05-24 07:54 UTC, lyutvs commented on notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
> +                        it.topic.substringBefore("_"),
수정 했습니다!

2023-05-24 14:56 UTC, jhhong0509 approved these changes

2023-05-25 11:12 UTC, merged