🔀 :: (#3) 알림 카테고리 엔티티
team-xquare/v1-service-notification pull request #5
Opened 2022-02-12 13:53 UTC by leeseojune53

2022-02-12 14:03 UTC, jhhong0509 commented on src/main/kotlin/io/github/v1servicenotification/domain/category/domain/NotificationCategory.kt
> +        @Column(columnDefinition = "TINYINT(1)")
이거 `@Column`어노테이션이랑 Validation이랑 같이 쓰면 ddl에서 적용이 안되는 것 같아서 `nullable = false`도 붙여주세요

2022-02-12 14:04 UTC, jhhong0509 commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-validation:2.6.3")
여기 버전을 명시한 이유가 뭔가요?

2022-02-14 08:37 UTC, smoothbear requested changes
코멘트 남겼습니다! 🙂

2022-02-14 08:37 UTC, smoothbear commented on src/main/kotlin/io/github/v1servicenotification/domain/category/domain/NotificationCategory.kt
> +)
질문입니다. 이 부분 단순 조회용 엔티티인가요?

2022-02-14 08:37 UTC, smoothbear commented on src/main/resources/application.yml
> +      ddl-auto: update
질문입니다. 이거 프로덕션에서는 `validate`로 바뀌는거죠? 아니면 아예 `development` config랑 `production` config를 구분하는 것도 괜찮겠습니다 😶

2022-02-14 08:37 UTC, smoothbear commented on build.gradle.kts
>      implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:2.2.6.RELEASE")
```suggestion
    implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:${Libs.AWS_MESSAGING}")
```
<br/>
다음과 같이 `buildSrc`를 활용하거나 아니면 아래와 같이 `gradle.properties`를 이용해서 버전관리를 하는 것이 좋을 것 같아요. 

gradle.properties
```
awsMessagingVersion = 2.2.6
```

build.gradle.kts
```kotlin
val awsMessagingVersion by project
```

```suggestion
    implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:${awsMessagingVersion}")
```

2022-02-14 09:05 UTC, leeseojune53 commented on src/main/kotlin/io/github/v1servicenotification/domain/category/domain/NotificationCategory.kt
> +        @Column(columnDefinition = "TINYINT(1)")
<img width="598" alt="스크린샷 2022-02-14 오후 6 05 30" src="https://user-images.githubusercontent.com/61784568/153833136-e1d35186-4034-4d8f-b4d9-e6d4c18351e0.png">

2022-02-14 09:06 UTC, leeseojune53 commented on build.gradle.kts
>      implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:2.2.6.RELEASE")
저렇게 관리하면 다른 AWS 라이브러리들을 사용할때도 동일한 변수를 사용하면되니까 버전 관리가 편리해지는건가?

2022-02-14 09:07 UTC, leeseojune53 commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-validation:2.6.3")
아잇 삭제하게씁니당

2022-02-14 09:18 UTC, leeseojune53 commented on build.gradle.kts
>      implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:2.2.6.RELEASE")
kotlin dsl 관련해서 읽을만한 레퍼런스좀 주세용 ㅜㅜ

2022-02-15 01:40 UTC, smoothbear commented on build.gradle.kts
>      implementation("org.springframework.cloud:spring-cloud-starter-aws-messaging:2.2.6.RELEASE")
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources
요기용

2022-02-15 01:42 UTC, smoothbear commented on src/main/kotlin/io/github/v1servicenotification/domain/category/domain/NotificationCategory.kt
> +)
엔티티 변경이 되냐 안되냐의 여부에 따라서 `val`이 아닌 `var`에 `private setter`를 활용하여 수정이 필요한 필드만 열어놓는 방식을 채용해야 할듯..

2022-02-15 13:10 UTC, merged